use std::collections::HashSet;
use std::fmt::Write as _;
use std::fs;

use anyhow::{Context, Result};

use crate::cli::Scope;
use crate::config::Config;
use crate::inventory::{Bastion, Resource};
use crate::{cache, paths, ssh};

const BASTION_ALIAS: &str = "scwx-bastion";

pub fn run(scope: &Scope, config: &Config) -> Result<()> {
    let inventory = cache::load_or_fetch(scope.freshness, config)?;
    let bastion = inventory.require_bastion()?;
    let servers: Vec<&Resource> = inventory
        .filtered(scope.env, &config.tags)
        .filter(|resource| resource.kind.is_server())
        .collect();

    let (content, host_count) = render(&servers, bastion, config)?;

    let path = paths::home_dir()?.join(".ssh/config.d/scaleway");
    let parent = path.parent().context("ssh config path has no parent")?;
    fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    let temp = path.with_extension("tmp");
    fs::write(&temp, &content).with_context(|| format!("writing {}", temp.display()))?;
    fs::rename(&temp, &path).with_context(|| format!("replacing {}", path.display()))?;

    println!("wrote {} ({host_count} hosts)", path.display());
    include_hint()?;
    Ok(())
}

fn include_hint() -> Result<()> {
    let main_config = paths::home_dir()?.join(".ssh/config");
    let content = fs::read_to_string(&main_config).unwrap_or_default();
    let included = content
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with("Include"))
        .any(|line| line.contains("config.d/scaleway") || line.contains("config.d/*"));
    if !included {
        eprintln!("hint: add 'Include config.d/scaleway' to ~/.ssh/config to activate the hosts");
    }
    Ok(())
}

fn key_lines(config: &Config) -> Result<String> {
    let Some(key) = config.ssh.key.as_deref() else {
        return Ok(String::new());
    };
    let key = paths::expand_tilde(key)?;
    Ok(format!(
        "    IdentityFile {}\n    IdentitiesOnly yes\n",
        key.display()
    ))
}

/// A name lands verbatim on a Host/HostName line: anything outside this set
/// could turn into a glob pattern or, with whitespace, extra directives.
fn is_safe_host_token(token: &str) -> bool {
    !token.is_empty()
        && token
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

fn render(servers: &[&Resource], bastion: &Bastion, config: &Config) -> Result<(String, usize)> {
    let key_lines = key_lines(config)?;
    let mut out = String::from("# Generated by scwx sync-ssh; do not edit.\n\n");

    write!(
        out,
        "Host {BASTION_ALIAS}\n    HostName {}\n    Port {}\n    User {}\n{key_lines}",
        bastion.ip, bastion.port, config.bastion.user
    )?;
    out.push_str(&ssh::option_config_lines(&ssh::HARDENING_OPTIONS));

    let mut seen = HashSet::new();
    for server in servers {
        let alias = server.display_name(&config.naming);
        if !is_safe_host_token(alias) || !is_safe_host_token(&server.name) {
            eprintln!(
                "warning: skipping {}: unsafe name for ssh config",
                server.name
            );
            continue;
        }
        if !seen.insert(alias.to_owned()) {
            continue;
        }
        write!(
            out,
            "\nHost {alias}\n    HostName {}\n    User {}\n    ProxyJump {BASTION_ALIAS}\n{key_lines}",
            server.name, config.ssh.user
        )?;
        out.push_str(&ssh::option_config_lines(&ssh::HARDENING_OPTIONS));
    }
    Ok((out, seen.len()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inventory::ResourceKind;

    fn server(name: &str) -> Resource {
        Resource {
            kind: ResourceKind::Instance,
            id: "id".to_owned(),
            name: name.to_owned(),
            zone: "fr-par-1".to_owned(),
            tags: vec![],
            endpoint_ip: None,
            endpoint_port: None,
        }
    }

    #[test]
    fn renders_bastion_and_deduplicated_hosts() {
        let mut config = Config::default();
        config.naming.strip_prefixes = vec!["platform-ingestor-".to_owned()];
        config.ssh.key = Some("/keys/id_ed25519".to_owned());
        let bastion = Bastion {
            ip: "5.6.7.8".to_owned(),
            port: 61000,
            zone: "fr-par-1".to_owned(),
        };
        let a = server("platform-ingestor-api-0");
        let dup1 = server("osrs-master-1");
        let dup2 = server("osrs-master-1");
        let evil = server("bad name\n  ProxyCommand evil");
        let servers = vec![&a, &dup1, &dup2, &evil];

        let (rendered, host_count) = render(&servers, &bastion, &config).unwrap();
        assert_eq!(host_count, 2);
        assert!(!rendered.contains("evil"));

        assert_eq!(
            rendered,
            "\
# Generated by scwx sync-ssh; do not edit.

Host scwx-bastion
    HostName 5.6.7.8
    Port 61000
    User bastion
    IdentityFile /keys/id_ed25519
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR

Host api-0
    HostName platform-ingestor-api-0
    User root
    ProxyJump scwx-bastion
    IdentityFile /keys/id_ed25519
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR

Host osrs-master-1
    HostName osrs-master-1
    User root
    ProxyJump scwx-bastion
    IdentityFile /keys/id_ed25519
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
"
        );
    }

    #[test]
    fn renders_without_identity_when_no_key_is_configured() {
        let bastion = Bastion {
            ip: "5.6.7.8".to_owned(),
            port: 61000,
            zone: "fr-par-1".to_owned(),
        };
        let (rendered, host_count) = render(&[], &bastion, &Config::default()).unwrap();
        assert_eq!(host_count, 0);
        assert!(!rendered.contains("IdentityFile"));
        assert!(!rendered.contains("IdentitiesOnly"));
    }
}
